[log]
enable = false
path = "/tmp/my-greeter.log"

[auth]
default_user = "gtlx"
auto_login = false

[branding]
title = "gtlx's machine"

[theme]
title = "cyan bold"
separator = "dark gray"
border = "white"
border_focus = "#FFA500"
text = "white"
text_focus = "#FFA500"
plugin = "green"
hint = "dark gray"
error = "red bold"
session = "dark gray"
session_focus = "white bold"
